import MockAdapter from 'axios-mock-adapter';
import {ApiInstance} from '@/app/api';
import type {ISupplyItem, ISupplySelect} from '@/entities/Supply/model/supply.types';

const SUPPLY_MOCKS: ISupplyItem[] = [
    {
        id: '1',
        number: '00001',
        date: '2026-08-01',
        organization: 'ООО "Альфа"',
        contractor: 'ИП Петров',
        supplyNumber: 'SUP-00001',
        quantity: 24,
        status: 'accepted',
        statusText: 'Принят без расхождений',
        acceptanceDate: '2026-08-02',
        deliveryTime: '2 дня',
        amount: 154000,
        comment: 'Без замечаний',
    },
    {
        id: '2',
        number: '00002',
        date: '2026-08-03',
        organization: 'ООО "Бета"',
        contractor: 'ООО "Логистика+"',
        supplyNumber: 'SUP-00002',
        quantity: 10,
        status: 'not_reserved',
        statusText: 'Не зарезервирован',
        acceptanceDate: '2026-08-05',
        deliveryTime: '3 дня',
        amount: 89000,
        comment: 'Требуется резервирование',
    },
    {
        id: '3',
        number: '00001',
        date: '2026-08-01',
        organization: 'ООО "Альфа"',
        contractor: 'ИП Петров',
        supplyNumber: 'SUP-00001',
        quantity: 24,
        status: 'accepted',
        statusText: 'Принят без расхождений',
        acceptanceDate: '2026-08-02',
        deliveryTime: '2 дня',
        amount: 154000,
        comment: 'Без замечаний',
    },
    {
        id: '4',
        number: '00002',
        date: '2026-08-03',
        organization: 'ООО "Бета"',
        contractor: 'ООО "Логистика+"',
        supplyNumber: 'SUP-00002',
        quantity: 10,
        status: 'not_reserved',
        statusText: 'Не зарезервирован',
        acceptanceDate: '2026-08-05',
        deliveryTime: '3 дня',
        amount: 89000,
        comment: 'Требуется резервирование',
    },
    {
        id: '5',
        number: '00001',
        date: '2026-08-01',
        organization: 'ООО "Альфа"',
        contractor: 'ИП Петров',
        supplyNumber: 'SUP-00001',
        quantity: 24,
        status: 'accepted',
        statusText: 'Принят без расхождений',
        acceptanceDate: '2026-08-02',
        deliveryTime: '2 дня',
        amount: 154000,
        comment: 'Без замечаний',
    },
    {
        id: '6',
        number: '00002',
        date: '2026-08-03',
        organization: 'ООО "Бета"',
        contractor: 'ООО "Логистика+"',
        supplyNumber: 'SUP-00002',
        quantity: 10,
        status: 'not_reserved',
        statusText: 'Не зарезервирован',
        acceptanceDate: '2026-08-05',
        deliveryTime: '3 дня',
        amount: 89000,
        comment: 'Требуется резервирование',
    },
    {
        id: '7',
        number: '00001',
        date: '2026-08-01',
        organization: 'ООО "Альфа"',
        contractor: 'ИП Петров',
        supplyNumber: 'SUP-00001',
        quantity: 24,
        status: 'accepted',
        statusText: 'Принят без расхождений',
        acceptanceDate: '2026-08-02',
        deliveryTime: '2 дня',
        amount: 154000,
        comment: 'Без замечаний',
    },
    {
        id: '8',
        number: '00002',
        date: '2026-08-03',
        organization: 'ООО "Бета"',
        contractor: 'ООО "Логистика+"',
        supplyNumber: 'SUP-00002',
        quantity: 10,
        status: 'not_reserved',
        statusText: 'Не зарезервирован',
        acceptanceDate: '2026-08-05',
        deliveryTime: '3 дня',
        amount: 89000,
        comment: 'Требуется резервирование',
    },
    {
        id: '9',
        number: '00001',
        date: '2026-08-01',
        organization: 'ООО "Альфа"',
        contractor: 'ИП Петров',
        supplyNumber: 'SUP-00001',
        quantity: 24,
        status: 'accepted',
        statusText: 'Принят без расхождений',
        acceptanceDate: '2026-08-02',
        deliveryTime: '2 дня',
        amount: 154000,
        comment: 'Без замечаний',
    },
    {
        id: '10',
        number: '00002',
        date: '2026-08-03',
        organization: 'ООО "Бета"',
        contractor: 'ООО "Логистика+"',
        supplyNumber: 'SUP-00002',
        quantity: 10,
        status: 'not_reserved',
        statusText: 'Не зарезервирован',
        acceptanceDate: '2026-08-05',
        deliveryTime: '3 дня',
        amount: 89000,
        comment: 'Требуется резервирование',
    },
];
const SUPPLY_SELECT: ISupplySelect[] = [
    {id: 1, label: 'Все', value: 'all'},
    {id: 2, label: 'Основной', value: 'main'},
    {id: 3, label: 'Резервный', value: 'reserve'},
];

const mock = new MockAdapter(ApiInstance, {delayResponse: 800});

mock.onGet('/supplies').reply(200, SUPPLY_MOCKS);
mock.onGet('/supplies/select').reply(200, SUPPLY_SELECT);
